version: '3.8'

services:
  app:
    image: murick/flask_db_app
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=8000
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/database_flask
    ports:
    - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_flask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

